# Generated by Django 4.2.5 on 2023-09-10 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainAPI", "0002_category_menuitem_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="category",
            field=models.ForeignKey(
                db_constraint=False,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="mainAPI.category",
            ),
        ),
    ]
